In [1]:
import numpy as np
import csv

In [2]:
path_csv = "Training Sites and Occupancy/ch1_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch1_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(66,)
(66,)
[[1.         0.95431217]
 [0.95431217 1.        ]]


In [3]:
path_csv = "Training Sites and Occupancy/ch2_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch2_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(289,)
(289,)
[[1.         0.95167572]
 [0.95167572 1.        ]]


In [4]:
path_csv = "Training Sites and Occupancy/ch3_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch3_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(91,)
(91,)
[[1.         0.96967847]
 [0.96967847 1.        ]]


In [5]:
path_csv = "Training Sites and Occupancy/ch4_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch4_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(535,)
(535,)
[[1.         0.96885564]
 [0.96885564 1.        ]]


In [6]:
path_csv = "Training Sites and Occupancy/ch5_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch5_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(195,)
(195,)
[[1.        0.9568667]
 [0.9568667 1.       ]]


In [7]:
path_csv = "Training Sites and Occupancy/ch6_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch6_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(87,)
(87,)
[[1.         0.96255452]
 [0.96255452 1.        ]]


In [8]:
path_csv = "Training Sites and Occupancy/ch7_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch7_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(382,)
(382,)
[[1.         0.96999296]
 [0.96999296 1.        ]]


In [9]:
path_csv = "Training Sites and Occupancy/ch8_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch8_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(188,)
(188,)
[[1.         0.96477656]
 [0.96477656 1.        ]]


In [10]:
path_csv = "Training Sites and Occupancy/ch9_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch9_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(142,)
(142,)
[[1.        0.9560886]
 [0.9560886 1.       ]]


In [11]:
path_csv = "Training Sites and Occupancy/ch10_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch10_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(252,)
(252,)
[[1.         0.29230442]
 [0.29230442 1.        ]]


In [12]:
path_csv = "Training Sites and Occupancy/ch11_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch11_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(251,)
(251,)
[[1.         0.97453463]
 [0.97453463 1.        ]]


In [13]:
path_csv = "Training Sites and Occupancy/ch12_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch12_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(358,)
(358,)
[[1.        0.9704662]
 [0.9704662 1.       ]]


In [14]:
path_csv = "Training Sites and Occupancy/ch13_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch13_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(331,)
(331,)
[[1.         0.97161988]
 [0.97161988 1.        ]]


In [15]:
path_csv = "Training Sites and Occupancy/ch14_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch14_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(269,)
(269,)
[[1.         0.97129411]
 [0.97129411 1.        ]]


In [16]:
path_csv = "Training Sites and Occupancy/ch15_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch15_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(390,)
(390,)
[[1.         0.96350462]
 [0.96350462 1.        ]]


In [17]:
path_csv = "Training Sites and Occupancy/ch16_training.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Training)/ch16_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(345,)
(345,)
[[1.         0.96377586]
 [0.96377586 1.        ]]
