In [1]:
import numpy as np
import csv

In [2]:
data = np.loadtxt("Test Sites and Occupancy/ch1_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch1_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(1616,)
(1616,)
[[1.         0.87818487]
 [0.87818487 1.        ]]


In [3]:
data = np.loadtxt("Test Sites and Occupancy/ch2_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch2_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(7195,)
(7195,)
[[1.         0.83385444]
 [0.83385444 1.        ]]


In [4]:
data = np.loadtxt("Test Sites and Occupancy/ch3_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch3_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(2358,)
(2358,)
[[1.         0.87930609]
 [0.87930609 1.        ]]


In [5]:
data = np.loadtxt("Test Sites and Occupancy/ch4_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch4_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(13249,)
(13249,)
[[1.         0.87793794]
 [0.87793794 1.        ]]


In [6]:
data = np.loadtxt("Test Sites and Occupancy/ch5_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch5_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(4955,)
(4955,)
[[1.         0.88109766]
 [0.88109766 1.        ]]


In [7]:
data = np.loadtxt("Test Sites and Occupancy/ch6_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch6_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(2277,)
(2277,)
[[1.         0.88025175]
 [0.88025175 1.        ]]


In [8]:
data = np.loadtxt("Test Sites and Occupancy/ch7_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch7_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(9451,)
(9451,)
[[1.         0.88693558]
 [0.88693558 1.        ]]


In [9]:
data = np.loadtxt("Test Sites and Occupancy/ch8_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch8_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(4658,)
(4658,)
[[1.         0.87932675]
 [0.87932675 1.        ]]


In [10]:
data = np.loadtxt("Test Sites and Occupancy/ch9_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch9_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(3682,)
(3682,)
[[1.        0.8737436]
 [0.8737436 1.       ]]


In [11]:
data = np.loadtxt("Test Sites and Occupancy/ch10_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch10_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(6343,)
(6343,)
[[1.         0.23632026]
 [0.23632026 1.        ]]


In [12]:
data = np.loadtxt("Test Sites and Occupancy/ch11_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch11_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(6075,)
(6075,)
[[1.         0.88274832]
 [0.88274832 1.        ]]


In [13]:
data = np.loadtxt("Test Sites and Occupancy/ch12_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch12_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(8961,)
(8961,)
[[1.         0.87950619]
 [0.87950619 1.        ]]


In [14]:
data = np.loadtxt("Test Sites and Occupancy/ch13_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch13_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(8151,)
(8151,)
[[1.         0.88596192]
 [0.88596192 1.        ]]


In [15]:
data = np.loadtxt("Test Sites and Occupancy/ch14_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch14_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(6795,)
(6795,)
[[1.         0.87908433]
 [0.87908433 1.        ]]


In [16]:
data = np.loadtxt("Test Sites and Occupancy/ch15_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch15_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(9584,)
(9584,)
[[1.         0.87680443]
 [0.87680443 1.        ]]


In [18]:
data = np.loadtxt("Test Sites and Occupancy/ch16_testing.csv",delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('Chromosome Prediction Results (Testing)/ch16_levelp(f).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(8224,)
(8224,)
[[1.         0.87877805]
 [0.87877805 1.        ]]
